- hosts: all
  tasks:
    - name: install nala
      apt:
        name: nala
        state: latest
        update_cache: true
      when: ansible_distribution_file_variety == "Debian"
      when: ansible_distribution_major_version in ["12","23"]
